spring:
  datasource:
    url: jdbc:postgresql://171.244.39.179:5432/mars
    username: mars
    password: mars
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # hoặc "none", "validate", "create", "create-drop"
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 8d3hY7wJn$XyPq#b4!Gz@L2mFzqM9aWr
  expiration: 86400000 # 1 day

file:
  upload-dir: uploads/images

swagger:
  # server-url:  https://mars-admin.gsolutions.net.vn/api
  server-url: http://localhost:8080
